'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class RoomFacility extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      RoomFacility.belongsTo(models.Room, {foreignKey: "RoomID"})
    }
  }
  RoomFacility.init({
    Name: DataTypes.STRING,
    Description: DataTypes.STRING,
    RoomID: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'Rooms', // Ensure this matches the table name generated by Sequelize
        key: 'id',
      },
      validate: {
        isInt: true,
        notNull: {
          msg: "RoomID cannot be null"
        },
      }
    }
  }, {
    sequelize,
    modelName: 'RoomFacility',
  });
  return RoomFacility;
};